Import ('env')

src_files = [
    'bdd_accessors.c',
    'bdd_create_destroy.c',
    'bdd_impl.c',
    'bdd_ops.c',
    'bdd_pair.c',
    'bdd_pair_ht.c',
    'hash_pair.c',
    'node.c',
    'node_ht.c',
    'node_vec.c',
    ]

env.StaticLibrary ('bdd', src_files)
